# Makefile for Program TJ

all:
	(cd TJ_Source; make)
	(cd WriteEFIT_Source; make)
	(cd Flux_Source; make)

clean:

	(cd TJ_Source; make clean)
	(cd WriteEFIT_Source; make clean)
	(cd Flux_Source; make clean)
